// servers/preview/templates/vue/src/App.vue
<script setup lang="ts">
</script>

<template>
  <div class="min-h-screen bg-gray-50 flex items-center justify-center">
    <div class="text-center">
      <h1 class="text-4xl font-bold text-gray-900 mb-4">UI Inspector Preview</h1>
      <p class="text-gray-600">코드를 생성하면 여기에 미리보기가 표시됩니다</p>
    </div>
  </div>
</template>

// servers/preview/templates/react/src/App.tsx
export default function App() {
  return (
    <div className="min-h-screen bg-gray-50 flex items-center justify-center">
      <div className="text-center">
        <h1 className="text-4xl font-bold text-gray-900 mb-4">UI Inspector Preview</h1>
        <p className="text-gray-600">코드를 생성하면 여기에 미리보기가 표시됩니다</p>
      </div>
    </div>
  );
}
